active_project_id: bd095fd6-5186-4eb3-9071-ecc5bb1162f1
active_stack_id: 574ca940-75af-4300-9b73-f82ac9630c7e
analytics_opt_in: true
store:
  backup_directory: D:\aui\Ayoub\Spring_2026\AI for Digital Transformation\Project\Milestone
    4 - Model Development and Evaluation\CSC5382-Project\Milestone_4-Model_Dev\.zen\database_backup
  backup_strategy: in-memory
  database: D:\aui\Ayoub\Spring_2026\AI for Digital Transformation\Project\Milestone
    4 - Model Development and Evaluation\CSC5382-Project\Milestone_4-Model_Dev\.zen\local_stores\default_zen_store/zenml.db
  driver: sqlite
  max_overflow: 20
  pool_pre_ping: true
  pool_size: 20
  secrets_store:
    type: sql
  ssl: false
  ssl_verify_server_cert: false
  type: sql
  url: sqlite:///D:\aui\Ayoub\Spring_2026\AI for Digital Transformation\Project\Milestone
    4 - Model Development and Evaluation\CSC5382-Project\Milestone_4-Model_Dev\.zen\local_stores\default_zen_store/zenml.db
user_id: f94e6de9-59b9-4f94-8c78-fb1eab9a4534
version: 0.94.1
